/home2/kskuhlman/env/acute/lib/python2.4/nose-0.10.0a2-py2.4.egg/nose/plugins/manager.py:291: UserWarning: Module nose was already imported from /home2/kskuhlman/env/acute/lib/python2.4/nose-0.10.0a2-py2.4.egg/nose/__init__.pyc, but /home2/kskuhlman/projects/acute-dbapi is being added to sys.path
  import pkg_resources
...................................................U...........
======================================================================
Unsupported: test_callproc (__main__.TestSQLProcs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home2/kskuhlman/projects/acute-dbapi/acute/nose_plugins/requires.py", line 91, in newfunc
    raise(Unsupported)
Unsupported

----------------------------------------------------------------------
Ran 63 tests in 4.026s

OK
